package main

import (
	"context"
	_ "embed"
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/usageflow/usageflow-go-middleware/v2/pkg/config"
	"github.com/usageflow/usageflow-go-middleware/v2/pkg/middleware"
	"github.com/usageflow/usageflow-go-middleware/v2/pkg/tracker"
)

//go:embed static/index.html
var indexHTML []byte

type chatRequest struct {
	Message string `json:"message" binding:"required"`
}

type chatResponse struct {
	Reply          string                       `json:"reply"`
	Intent         string                       `json:"intent"`
	Model          string                       `json:"model"`
	PromptTokens   int                          `json:"promptTokens"`
	ResponseTokens int                          `json:"responseTokens"`
	Provider       string                       `json:"provider,omitempty"`
	LocalCallChain []tracker.FunctionCallRecord `json:"localCallChain,omitempty"`
}

type chatService struct{}

func (chatService) Chat(ctx context.Context, message string) (chatResponse, error) {
	normalized := normalizeMessage(ctx, message)
	if normalized == "" {
		return chatResponse{}, fmt.Errorf("message cannot be empty")
	}

	intent := classifyIntent(ctx, normalized)

	completion, err := llmCompletion(ctx, normalized)
	if err != nil {
		return chatResponse{}, fmt.Errorf("openai: %w", err)
	}

	reply := ""
	if len(completion.Choices) > 0 {
		reply = strings.TrimSpace(completion.Choices[0].Message.Content)
	}
	if reply == "" {
		reply = generateReply(ctx, normalized, intent)
	}

	promptTokens := int(completion.Usage.PromptTokens)
	responseTokens := int(completion.Usage.CompletionTokens)
	if promptTokens == 0 {
		promptTokens = estimateTokens(ctx, normalized)
	}
	if responseTokens == 0 {
		responseTokens = estimateTokens(ctx, reply)
	}

	model := completion.Model
	if model == "" {
		model = "gpt-4o-mini"
	}

	return chatResponse{
		Reply:          reply,
		Intent:         intent,
		Model:          model,
		PromptTokens:   promptTokens,
		ResponseTokens: responseTokens,
		Provider:       "openai",
	}, nil
}

func normalizeMessage(ctx context.Context, message string) string {
	_ = ctx
	return strings.Join(strings.Fields(strings.TrimSpace(message)), " ")
}

func classifyIntent(ctx context.Context, message string) string {
	_ = ctx
	lower := strings.ToLower(message)
	switch {
	case strings.Contains(lower, "usage") || strings.Contains(lower, "meter"):
		return "usageflow"
	case strings.Contains(lower, "hello") || strings.Contains(lower, "hi"):
		return "greeting"
	case strings.Contains(lower, "help"):
		return "help"
	default:
		return "general"
	}
}

func generateReply(ctx context.Context, message, intent string) string {
	_ = ctx
	switch intent {
	case "usageflow":
		return "UsageFlow meters this request and reports the Go function call chain to your application."
	case "greeting":
		return "Hello! I am a Go chat server instrumented by UsageFlow."
	case "help":
		return "Try asking how UsageFlow tracks this Go request, then inspect the call chain below."
	default:
		return fmt.Sprintf("You said: %q. This response was generated by the instrumented Go backend.", message)
	}
}

func estimateTokens(ctx context.Context, text string) int {
	_ = ctx
	words := len(strings.Fields(text))
	if words == 0 {
		return 0
	}
	return words + 2
}

func main() {
	apiKey := strings.TrimSpace(os.Getenv("USAGEFLOW_API_KEY"))
	if apiKey == "" {
		log.Fatal("USAGEFLOW_API_KEY is required; copy .env.example to .env and add your application key")
	}
	if !openaiConfigured() {
		log.Fatal("OPENAI_API_KEY is required for live LLM replies (reuse the key from agents/js/examples/.env)")
	}

	r := gin.Default()
	uf := middleware.New(apiKey)
	// Keep health/UI polls out of traces so Console shows chat traffic clearly.
	uf.Whitelist(
		config.Route{Method: "GET", URL: "/"},
		config.Route{Method: "GET", URL: "/api/status"},
	)
	r.Use(uf.RequestInterceptor())

	service := chatService{}

	r.GET("/", func(c *gin.Context) {
		c.Data(http.StatusOK, "text/html; charset=utf-8", indexHTML)
	})

	r.GET("/api/status", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"connected":        uf.IsConnected(),
			"discoveryEnabled": tracker.IsEnabled(),
			"openaiConfigured": openaiConfigured(),
			"llmProvider":      "openai",
			"llmModel":         "gpt-4o-mini",
			"wsURL":            "wss://api.usageflow.io/ws",
			"service":          "usageflow-go-chat",
			"timestamp":        time.Now().UTC().Format(time.RFC3339),
			"hint":             "In Console, monitor POST /api/chat on the app that owns this uf_live key",
		})
	})

	r.POST("/api/chat", func(c *gin.Context) {
		var request chatRequest
		if err := c.ShouldBindJSON(&request); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "message is required"})
			return
		}

		response, err := service.Chat(c.Request.Context(), request.Message)
		if err != nil {
			c.JSON(http.StatusBadGateway, gin.H{"error": err.Error()})
			return
		}

		// Exposed only by this demo so you can see exactly what is also sent
		// through report_call_chain after the HTTP handler completes.
		response.LocalCallChain = tracker.GetCallChain(c.Request.Context())
		c.JSON(http.StatusOK, response)
	})

	port := os.Getenv("PORT")
	if port == "" {
		port = "8081"
	}

	log.Printf("UsageFlow Go chat: http://127.0.0.1:%s (OpenAI gpt-4o-mini)", port)
	if err := r.Run(":" + port); err != nil {
		log.Fatal(err)
	}
}
